CraigslistKnockoff/CraigslistKnockoff/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('my_app/', include('my_app.urls')),
]

CraigslistKnockoff/my_app/urls.py
from django.urls import path

from . import views

app_name = 'my_app'
urlpatterns = [
    path('', views.home, name='home'),
    path('new_search', views.new_search, name='new_search')
]

CraigslistKnockoff/my_app/models.py
from django.db import models

class Search(models.Model):
    search = models.CharField(max_length=500)
    created = models.DateTimeField(auto_now=True)

    def __str__(self):
        return '{}'.format(self.search)

    class Meta:
        verbose_name_plural = 'Searches'

CraigslistKnockoff/my_app/views.py
import requests
from django.shortcuts import render
from bs4 import BeautifulSoup

def home(request):
    return render(request, 'my_app/base.html')

def new_search(request):
    search = request.GET.get('search_text')
    results = {
        'search': search
    }
    return render(request, 'my_app/new_search.html', results)

CraigslistKnockoff/my_app/templates/my_app/base.html
{% load staticfiles %}
{% load static %}

<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>CraigslistKnockoff</title>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <link rel="stylesheet" href="{% static "my_app/style.css" %}">
    <link 
        rel="stylesheet" 
        href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"
    >
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>
<nav>
    <div class="container nav-wrapper">
        <a href="{% url 'my_app:home' %}" class="brand-logo">CraigslistKnockoff</a>
        <ul id="nav-mobile" class="right">
            <li><a href="{% url 'my_app:home' %}">Home</a></li>
        </ul>
    </div>
</nav>

<body>
    <div class="container">
        <h3 style="text-align: center">
        What do you want to search for on CraigslistKnockoff List?
        </h3>
        <div class="row">
            <div class="col s4">
                <!-- Promo Content 1 goes here -->
                <div class="center">
                    <i class="large material-icons" style="color: #EE6E73">
                        flash_on
                    </i>
                    <p style="color: #EE6E73">Fast craigslist web scraper</p>
                    <p class="light center">Scrape away right here with a beautiful GUI</p>
                </div>
            </div>
            <div class="col s4">
                <!-- Promo Content 2 goes here -->
                <div class="center">
                    <i class="large material-icons" style="color: orange">camera</i>
                    <p style="color: orange">Filter your searches</p>
                    <p class="light center">
                        We built in functionality to filter based on pricing.
                    </p>
                </div>
            </div>
            <div class="col s4">
                <!-- Promo Content 3 goes here -->
                <div class="center">
                    <i class="large material-icons" style="color: blue">chrome_reader_mode</i>
                    <p style="color: blue">A much sexier front-end to Craigslist</p>
                    <p class="light center">We built this with LUV</p> 
                </div>
            </div>
        </div>
        <form method="GET" action="{% url 'my_app:new_search' %}">
            {% if search %}
                 <input type="text" name="search_text" placeholder="{{search | title}}"}>
            {% else %} <input type="text" name="search_text" placeholder="SEARCH">
            {% endif %}
            <button class="btn waves-effect waves-light">
                SEND
                <i class="material-icons right">send</i>
            </button>
        </form>
        {% block content %}
        {% endblock content %}
    </div>

<script scr="ttps://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</body>
</html>

CraigslistKnockoff/my_app/templates/my_app/new_search.html
{% extends 'my_app/base.html' %}

{% block content %}
    {% if available_items %}
        <div class="row">
            <div class="col s4">
                <div class="card">
                    <div class="card-image">
                        <a href="/"><img src="/"></a>
                    </div>
                    <div class="card-content">
                        <p>TEST</p>
                    </div>
                    <div class="card-action">
                        <a href="/">View Listing: Price TEST PRICE</a>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}
{% endblock content %}